import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy for FixMyRide",
  description:
    "This Privacy Policy describes FixMyRide’s policies and procedures on the collection, use, and disclosure of your information when you use the FixMyRide application in Pakistan. Last updated January 20, 2026. Contact: fixmyride.help@gmail.com",
  applicationName: "FixMyRide",
  authors: [{ name: "FixMyRide" }],
  keywords: [
    "FixMyRide",
    "Privacy Policy",
    "Vehicle service app",
    "Mechanic service app",
    "Pakistan",
    "Personal Data",
    "Usage Data",
    "Location",
    "Camera access",
    "Email",
  ],
  robots: { index: true, follow: true },
};

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-10 space-y-6">
      <h1 className="text-3xl font-bold">Privacy Policy for FixMyRide</h1>
      <p className="text-sm text-muted-foreground">Last updated: January 20, 2026</p>

      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        FixMyRide application (the "Service"). It also explains Your privacy
        rights and how the law protects You.
      </p>

      <p>
        We use Your Personal Data to provide, operate, and improve the Service.
        By using the Service, You agree to the collection and use of information
        in accordance with this Privacy Policy.
      </p>

      <h2 className="text-xl font-bold mt-8">1. Interpretation and Definitions</h2>

      <h3 className="font-semibold mt-4">1.1 Interpretation</h3>
      <p>
        Words with capitalized initial letters have meanings defined under the
        following conditions. These definitions apply whether the terms appear
        in singular or plural form.
      </p>

      <h3 className="font-semibold mt-4">1.2 Definitions</h3>
      <ul className="list-disc pl-6 space-y-1">
        <li><b>Account:</b> A unique account created for You to access our Service or parts of our Service.</li>
        <li><b>Application:</b> The software program provided by the Company and downloaded by You on any electronic device, named FixMyRide.</li>
        <li><b>Company:</b> (referred to as "the Company", "We", "Us", or "Our") refers to FixMyRide.</li>
        <li><b>Country:</b> Pakistan.</li>
        <li><b>Device:</b> Any device that can access the Service, such as a computer, smartphone, or tablet.</li>
        <li><b>Personal Data:</b> Any information that relates to an identified or identifiable individual.</li>
        <li><b>Service:</b> The FixMyRide Application.</li>
        <li><b>Service Provider:</b> Any natural or legal person who processes data on behalf of the Company, including third-party companies or individuals who help operate, analyze, or improve the Service.</li>
        <li><b>Usage Data:</b> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><b>You:</b> The individual accessing or using the Service, or the legal entity on behalf of which such individual is accessing or using the Service.</li>
      </ul>

      <h2 className="text-xl font-bold mt-8">2. Collecting and Using Your Personal Data</h2>

      <h3 className="font-semibold mt-4">2.1 Types of Data Collected</h3>

      <h4 className="font-semibold mt-2">2.1.1 Personal Data</h4>
      <p>While using Our Service, We may ask You to provide certain personally identifiable information:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Account role (User or Mechanic)</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="font-semibold mt-2">2.1.2 Usage Data</h4>
      <p>
        Usage Data is collected automatically when using the Service and may include
        your IP address, device type, operating system, application version, pages visited,
        time spent, unique device identifiers, and other diagnostic data.
      </p>

      <h4 className="font-semibold mt-2">2.1.3 Information Collected While Using the Application</h4>
      <ul className="list-disc pl-6 space-y-1">
        <li><b>Location information:</b> Used to match users with nearby mechanics and to enable accurate service requests and delivery.</li>
        <li><b>Camera and photo library access:</b> Allowing users to upload pictures related to vehicle issues or service requests.</li>
      </ul>
      <p>
        This information is used solely to provide and improve the Service. It may be uploaded
        to the Company’s servers and/or a Service Provider’s servers, or stored locally on Your device.
      </p>

      <h3 className="font-semibold mt-4">2.2 Use of Your Personal Data</h3>
      <ul className="list-disc pl-6 space-y-1">
        <li>To provide and maintain the Service, including monitoring usage and performance.</li>
        <li>To manage Your Account, including registration and access to features based on Your role.</li>
        <li>To facilitate service requests.</li>
        <li>To contact You via email, phone calls, SMS, or push notifications.</li>
        <li>To provide updates and offers, unless You choose to opt out.</li>
        <li>To manage Your requests, inquiries, or support issues.</li>
        <li>For business transfers such as mergers or acquisitions.</li>
        <li>For analytics and improvement of the Service.</li>
      </ul>

      <h2 className="text-xl font-bold mt-8">3. Retention of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only as long as necessary to fulfill the purposes outlined in this Privacy Policy
        and to comply with legal obligations, resolve disputes, and enforce agreements. Usage Data is generally retained for a shorter period.
      </p>

      <h2 className="text-xl font-bold mt-8">4. Transfer of Your Personal Data</h2>
      <p>
        Your information may be processed at the Company’s operating offices or other locations where Service Providers are based.
        This may involve transferring data outside Your country. By using the Service and submitting Your information, You consent to such transfers.
      </p>

      <h2 className="text-xl font-bold mt-8">5. Disclosure of Your Personal Data</h2>

      <h3 className="font-semibold mt-2">5.1 Business Transactions</h3>
      <p>If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. You will be notified before such transfer occurs.</p>

      <h3 className="font-semibold mt-2">5.2 Law Enforcement</h3>
      <p>The Company may disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>

      <h3 className="font-semibold mt-2">5.3 Other Legal Requirements</h3>
      <p>The Company may disclose Your Personal Data in good faith if such action is necessary to:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Comply with legal obligations</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate wrongdoing related to the Service</li>
        <li>Protect the safety of users or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h2 className="text-xl font-bold mt-8">6. Security of Your Personal Data</h2>
      <p>
        We take reasonable measures to protect Your Personal Data. However, no method of transmission over the Internet or electronic storage is completely secure.
      </p>

      <h2 className="text-xl font-bold mt-8">7. Children’s Privacy</h2>
      <p>
        The Service is intended for users aged 13 years and above. We do not knowingly collect Personal Data from children under 13.
        If You believe that a child has provided Us with Personal Data, please contact Us.
      </p>

      <h2 className="text-xl font-bold mt-8">8. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Changes will be posted on this page, and the "Last updated" date will be revised accordingly.
      </p>

      <h2 className="text-xl font-bold mt-8">9. Contact Us</h2>
      <p>If You have any questions about this Privacy Policy, You can contact Us:</p>
      <p className="font-semibold mt-2">By email: <a href="mailto:fixmyride.help@gmail.com" className="underline">fixmyride.help@gmail.com</a></p>
    </div>
  );
}
